import enum
from sqlalchemy import Column, String, Enum
from sqlalchemy.orm import relationship
from Database.config import Base
from CommonLayer.domain.autitable_entity import AuditableEntity


class DocumentType(str, enum.Enum):
    RUC = "RUC"
    DNI = "DNI"
    OTRO = "OTRO"


class PaymentCondition(str, enum.Enum):
    CONTADO = "CONTADO"
    CREDITO = "CREDITO"


class Customer(Base, AuditableEntity):
    __tablename__ = "customers"

    id = Column(String(50), primary_key=True, index=True)
    nombre = Column(String(200), nullable=False, index=True)
    tipo_documento = Column(String(10), nullable=False, default=DocumentType.DNI)
    numero_documento = Column(String(50), unique=True, nullable=False, index=True)
    direccion = Column(String(300), nullable=True)
    telefono = Column(String(30), nullable=True)
    email = Column(String(150), unique=True, nullable=True)
    condicion_pago = Column(String(20), nullable=False, default=PaymentCondition.CONTADO)

    # Reverse relationship: movements generated by this customer (sales)
    movements = relationship("Movement", back_populates="customer", foreign_keys="Movement.customer_id")
