from sqlalchemy import Column, String, Integer, Text
from sqlalchemy.orm import relationship
from Database.config import Base
from CommonLayer.domain.autitable_entity import AuditableEntity


class Supplier(Base, AuditableEntity):
    __tablename__ = "suppliers"

    id = Column(String(50), primary_key=True, index=True)
    nombre = Column(String(200), nullable=False, index=True)
    tipo_documento = Column(String(10), nullable=False, default="RUC")
    numero_documento = Column(String(50), unique=True, nullable=False, index=True)
    direccion = Column(String(300), nullable=True)
    telefono = Column(String(30), nullable=True)
    email = Column(String(150), unique=True, nullable=True)
    plazo_entrega_dias = Column(Integer, nullable=True)
    condiciones_compra = Column(Text, nullable=True)

    # Reverse relationship: movements generated by this supplier (purchases)
    movements = relationship("Movement", back_populates="supplier", foreign_keys="Movement.supplier_id")
